### ISSUE TITLE
Can I Ask if you have made caffe or tensorflow version of the model

### ISSUE THREAD

**Issue by yw2278** [YonghaoHe/LFFD-A-Light-and-Fast-Face-Detector-for-Edge-Devices#17]

**Comment by becauseofAI** [comment]
@yw2278 
The PyTorch preview version is released in [lffd branch](https://github.com/becauseofAI/refinanet/tree/lffd) of RefinaNet. Now you can try to train v2 version of the face task as same as the original mxnet version using this [script](https://github.com/becauseofAI/refinanet/blob/lffd/face_detection/config_farm/configuration_10_320_20L_5scales_v2.py).

**Comment by pram991** [comment]
@YonghaoHe  Do you have any scripts for converting the model to ONNX?

**Comment by YonghaoHe** [comment]
@pram991 The script is deploy_tensorrt/to_onnx.py
